---
title: "HW2"
author: "Don Redden"
date: "5/1/2019"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

Problem 1

I split the dataset into 2 files:

1. Essay_Train (contains only rows from Hamilton and Madison without filename column)
2. Essay_Test (contains only rows from disputed without filename column)
```{r}
library(dplyr)
Essay_Raw <- read.csv("/cloud/project/Disputed_Essay_data.csv")
Essay_Clean <- select (Essay_Raw,-c(filename))
Essay_Train <- filter(Essay_Clean, grepl('Hamilton|Madison', author))
Essay_Test <- filter(Essay_Clean, grepl('dispt', author))

```

Create data tree model

```{r}
library(rpart)
library(rpart.plot)
dtm <- rpart(author~., Essay_Train, method = "class")

rpart.plot(dtm)

p <- predict(dtm, Essay_Test, type = "class")

table(Essay_Test[,1],p)

```

Problem 2

```{r}
library(caret)
library(nnet)
library(ggplot2)
library(lattice)
library(e1071)

education <- read.csv("/cloud/project/xAPI-Edu-Data.csv", header = TRUE)

summary(education)

```

Preprocessing for Data

```{r}
# Is there missing data?
sum(is.na(education))

# calculate correlation matrix
correlationMatrix <- cor(education[,10:13])
# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.75)

education <-education[,-8]


```

Create test and train datasets

```{r}
set.seed(17)
# Stratified sampling
TrainingDataIndex <- createDataPartition(education$Class, p=0.75, list = FALSE)
# Create Training Data 
trainingData <- education[TrainingDataIndex,]
testData <- education[-TrainingDataIndex,]
TrainingParameters <- trainControl(method = "repeatedcv", number = 10, repeats=10)
```

Model with Neural Net

```{r}
# train model with neural networks
NNModel <- train(trainingData[,-17], trainingData$Class,
                  method = "nnet",
                  trControl= TrainingParameters,
                  preProcess=c("scale","center"),
                  na.action = na.omit
)

NNPredictions <-predict(NNModel, testData)
# Create confusion matrix
cmNN <-confusionMatrix(NNPredictions, testData$Class)

print(cmNN)
```

